sratunnel tests

diff --git a/tests/test-tools-with-server.sh.in b/tests/test-tools-with-server.sh.in
--- a/tests/test-tools-with-server.sh.in
+++ b/tests/test-tools-with-server.sh.in
@@ -1,7 +1,11 @@
-#!/bin/sh -e
+#
+# Copyright 2021-2016 Farsight Security, Inc.
+#
 
-SVCDIR=/etc/init.d
-RADTOOL=@builddir@/sratool/radtool
+#!/bin/sh
+
+SRATOOL=@builddir@/sratool/sratool
+SRATUNNEL=@builddir@/sratunnel/sratunnel
 DATADIR=@abs_top_srcdir@/tests/tool-tests-data/with-server
 
 #
@@ -11,7 +15,7 @@ DATADIR=@abs_top_srcdir@/tests/tool-tests-data/with-server
 #
 pgrep srad &> /dev/null
 if [ $? -ne 0 ]; then
-	echo "SRA server doesn't seem to be running, skipping tests.."
+	printf "SRA server doesn't seem to be running, skipping tests.."
 	exit 0
 fi
 
@@ -20,23 +24,74 @@ fi
 #
 set -o errexit
 
-echo 001000 test a successful connection to the SRA server
+printf "001000 test a successful connection to the SRA server\n"
 $SRATOOL -c $DATADIR/001000-connect | grep "OK USER valid"
 
-echo 001010 test an unsuccessful connection to the SRA server
+printf "\n001010 test an unsuccessful connection to the SRA server\n"
 $SRATOOL -c $DATADIR/001010-invalid-username | grep "ERROR USER invalid"
 
-echo 001020 test channel listing
+printf "\n001020 test channel listing\n"
 $SRATOOL -c $DATADIR/001020-list | grep "ch"
 
-echo 001030 test setting a channel watch
+printf "\n001030 test setting a channel watch\n"
 $SRATOOL -c $DATADIR/001030-set-watch| grep "OK WATCH"
 
-echo 001040 test setting a watch on an invalid channel
+printf "\n001040 test setting a watch on an invalid channel\n"
 $SRATOOL -c $DATADIR/001040-watch-invalid-channel | grep "ERROR WATCH unknown"
 
-echo 001050 test watching a channel
+printf "\n001050 test watching a channel\n"
 $SRATOOL -c $DATADIR/001050-watch-channel | egrep "OK CHANNEL ON|packet count limit exceeded"
 
-echo 001060 test watching a DNS tag
-$SRATOOL -c $DATADIR/001060-watch-dns | grep "OK CHANNEL ON|packet count limit exceeded"
+printf "\n001060 test watching a DNS tag\n"
+$SRATOOL -c $DATADIR/001060-watch-dns | egrep "OK CHANNEL ON|packet count limit exceeded"
+
+SRA_SERVER=tcp:valid-user@127.0.0.1,9999
+OUT_FILE=/tmp/sratunnel-test-nmsg.out
+NMSG_FILE=nmsg:file:$OUT_FILE
+NMSG_UDP=nmsg:udp:127.0.0.1,8888
+PID_FILE=/tmp/sratunnel-test.pid
+ARCHIVE_FILE=/tmp/sratunnel-test.tar
+
+printf "\n002000 test a simple sratunnel(1) transfer to a UDP port\n"
+$SRATUNNEL -s $SRA_SERVER -w ch=221 -c 221 -o $NMSG_UDP -C 3 -ddd | grep "OK USER valid"
+
+printf "\n002010 test a simple sratunnel(1) transfer to a nmsg file\n"
+$SRATUNNEL -s $SRA_SERVER -w ch=221 -c 221 -o $NMSG_FILE -C 3 -ddd | grep "OK USER valid"
+grep NMSG $OUT_FILE
+rm $OUT_FILE
+
+printf "\n002020 test the -P (pidfile) option in sratunnel(1)\n"
+$SRATUNNEL -s $SRA_SERVER -w ch=221 -c 221 -o $NMSG_UDP -dd -P $PID_FILE | grep "connected" & sleep 3; kill `cat $PID_FILE`
+
+printf "\n002030 test the -i (timestamp index) option in sratunnel(1)\n"
+$SRATUNNEL -s $SRA_SERVER -w ch=221 -c 221 -o $NMSG_FILE -dd -u -i 1 -C 100 | grep "wrote timestamp"
+test -e $OUT_FILE.mdb
+rm $OUT_FILE $OUT_FILE.mdb
+
+printf "\n002040 test the -I (max index size) option in sratunnel(1) without -i\n"
+$SRATUNNEL -s $SRA_SERVER -w ch=221 -c 221 -o $NMSG_FILE -dd -C3 -I 1
+rm $OUT_FILE
+
+set +o errexit
+
+printf "\n002050 test passing an invalid value to the -I (max index size) option in sratunnel(1)\n"
+$SRATUNNEL -s $SRA_SERVER -w ch=221 -c 221 -o $NMSG_FILE -dd -C3 -I 0 | grep "invalid"
+rm $OUT_FILE $OUT_FILE.mdb
+
+printf "\n002050 test the -i and -I options in sratunnel with too low values(1)\n"
+$SRATUNNEL -s $SRA_SERVER -w ch=221 -c 221 -o $NMSG_FILE -dd -C3 -I 1 -i 1 -u | grep "out of memory"
+rm $OUT_FILE $OUT_FILE.mdb
+
+set -o errexit
+
+printf "\n002070 test the -i and -I options in sratunnel with appropriate values(1)\n"
+$SRATUNNEL -s $SRA_SERVER -w ch=221 -c 221 -o $NMSG_FILE -dd -C30 -I 5 -i 3 -u | grep "writing timestamp offsets"
+rm $OUT_FILE $OUT_FILE.mdb
+
+printf "\n002080 test the -k (kickfile) option in sratunnel(1)\n"
+$SRATUNNEL -s $SRA_SERVER -w ch=221 -c 221 -o $NMSG_FILE -dd -C 1000 -P $PID_FILE -k 'tar uvf '$ARCHIVE_FILE' --remove-files -P' & sleep 1; kill `cat $PID_FILE`
+sleep 1
+test -e $ARCHIVE_FILE
+rm $ARCHIVE_FILE
+
+printf "\nTests concluded without issues.\n"
